### ISSUE TITLE
SIGTERM handling

### ISSUE THREAD

**Issue by JxBP** [TheMysterys/Mineclub-Link#2]
I saw that there is a handler for SIGINT to gracefully shutdown so it would only make sense for the program to also handle SIGTERM signals and do the same.

According to POSIX standards the SIGTERM signal is used to terminate a process while still giving it the opportunity to clean up resources etc.

See:
[Wikipedia](https://en.m.wikipedia.org/wiki/Signal_(IPC)#SIGTERM)

**Comment by TheMysterys** [comment]
Could you provide more information please

**Comment by JxBP** [comment]
See about SIGTERM [here](https://stackoverflow.com/questions/4042201/how-does-sigint-relate-to-the-other-termination-signals-such-as-sigterm-sigquit)

The lines of code I am referring to are in main.js from line 295 to end
